import type { UserGoal } from '@/types/user'
import type { Exercise } from '@/types/exercise'
import type { CaptureGuide } from '@/types/posture'

export const GOALS: UserGoal[] = [
  {
    id: 'posture_correction',
    name: 'Posture Correction',
    nameKo: '자세 교정',
    icon: '🧘',
    description: 'Improve your overall posture',
    descriptionKo: '전반적인 자세를 개선합니다',
  },
  {
    id: 'forward_head',
    name: 'Forward Head Fix',
    nameKo: '거북목 개선',
    icon: '🦒',
    description: 'Fix forward head posture',
    descriptionKo: '거북목 자세를 교정합니다',
  },
  {
    id: 'back_pain',
    name: 'Back Pain Relief',
    nameKo: '허리 통증 완화',
    icon: '💆',
    description: 'Relieve lower back pain',
    descriptionKo: '허리 통증을 완화합니다',
  },
  {
    id: 'shoulder_pain',
    name: 'Shoulder Pain Relief',
    nameKo: '어깨 통증 완화',
    icon: '💪',
    description: 'Relieve shoulder tension',
    descriptionKo: '어깨 긴장을 완화합니다',
  },
  {
    id: 'rehabilitation',
    name: 'Rehabilitation',
    nameKo: '재활 운동',
    icon: '🏥',
    description: 'Recover from injuries',
    descriptionKo: '부상에서 회복합니다',
  },
  {
    id: 'body_shape',
    name: 'Body Shape Correction',
    nameKo: '체형 교정',
    icon: '🎯',
    description: 'Correct body alignment',
    descriptionKo: '체형을 교정합니다',
  },
  {
    id: 'exercise_habit',
    name: 'Exercise Habit',
    nameKo: '운동 습관 만들기',
    icon: '📅',
    description: 'Build a regular exercise routine',
    descriptionKo: '규칙적인 운동 습관을 만듭니다',
  },
  {
    id: 'stretching',
    name: 'Stretching',
    nameKo: '스트레칭',
    icon: '🤸',
    description: 'Improve flexibility',
    descriptionKo: '유연성을 향상시킵니다',
  },
  {
    id: 'strength',
    name: 'Strength Building',
    nameKo: '근력 강화',
    icon: '🏋️',
    description: 'Build muscle strength',
    descriptionKo: '근력을 강화합니다',
  },
]

export const PAIN_AREAS = [
  { id: 'neck', name: 'Neck', nameKo: '목', x: 50, y: 12 },
  { id: 'left_shoulder', name: 'Left Shoulder', nameKo: '왼쪽 어깨', x: 30, y: 18 },
  { id: 'right_shoulder', name: 'Right Shoulder', nameKo: '오른쪽 어깨', x: 70, y: 18 },
  { id: 'upper_back', name: 'Upper Back', nameKo: '등 상부', x: 50, y: 25 },
  { id: 'lower_back', name: 'Lower Back', nameKo: '허리', x: 50, y: 38 },
  { id: 'left_elbow', name: 'Left Elbow', nameKo: '왼쪽 팔꿈치', x: 20, y: 35 },
  { id: 'right_elbow', name: 'Right Elbow', nameKo: '오른쪽 팔꿈치', x: 80, y: 35 },
  { id: 'left_wrist', name: 'Left Wrist', nameKo: '왼쪽 손목', x: 15, y: 48 },
  { id: 'right_wrist', name: 'Right Wrist', nameKo: '오른쪽 손목', x: 85, y: 48 },
  { id: 'left_hip', name: 'Left Hip', nameKo: '왼쪽 골반', x: 38, y: 48 },
  { id: 'right_hip', name: 'Right Hip', nameKo: '오른쪽 골반', x: 62, y: 48 },
  { id: 'left_knee', name: 'Left Knee', nameKo: '왼쪽 무릎', x: 40, y: 68 },
  { id: 'right_knee', name: 'Right Knee', nameKo: '오른쪽 무릎', x: 60, y: 68 },
  { id: 'left_ankle', name: 'Left Ankle', nameKo: '왼쪽 발목', x: 40, y: 88 },
  { id: 'right_ankle', name: 'Right Ankle', nameKo: '오른쪽 발목', x: 60, y: 88 },
]

export const EXERCISES: Exercise[] = [
  {
    id: 'squat',
    name: 'Squat',
    nameKo: '스쿼트',
    description: 'A fundamental lower body exercise',
    descriptionKo: '기본적인 하체 운동입니다',
    category: 'strength',
    difficulty: 'beginner',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    instructions: [
      'Stand with feet shoulder-width apart',
      'Lower your body by bending knees',
      'Keep your back straight',
      'Return to starting position',
    ],
    instructionsKo: [
      '발을 어깨 너비로 벌리고 서세요',
      '무릎을 굽혀 몸을 낮추세요',
      '등을 곧게 유지하세요',
      '시작 자세로 돌아가세요',
    ],
    checkpoints: [
      {
        name: 'Knee angle',
        nameKo: '무릎 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['hip', 'knee', 'ankle'],
      },
    ],
    caloriesPerRep: 0.5,
  },
  {
    id: 'lunge',
    name: 'Lunge',
    nameKo: '런지',
    description: 'Single leg strengthening exercise',
    descriptionKo: '한 쪽 다리 강화 운동입니다',
    category: 'strength',
    difficulty: 'beginner',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    instructions: [
      'Stand with feet hip-width apart',
      'Step forward with one leg',
      'Lower your hips until both knees are bent',
      'Push back to starting position',
    ],
    instructionsKo: [
      '발을 골반 너비로 벌리고 서세요',
      '한 발을 앞으로 내딛으세요',
      '양 무릎이 구부러질 때까지 엉덩이를 낮추세요',
      '시작 자세로 돌아가세요',
    ],
    checkpoints: [
      {
        name: 'Front knee angle',
        nameKo: '앞 무릎 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['hip', 'knee', 'ankle'],
      },
    ],
    caloriesPerRep: 0.6,
  },
  {
    id: 'pushup',
    name: 'Push-up',
    nameKo: '푸쉬업',
    description: 'Classic upper body exercise',
    descriptionKo: '클래식한 상체 운동입니다',
    category: 'strength',
    difficulty: 'intermediate',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    targetMuscles: ['chest', 'triceps', 'shoulders'],
    instructions: [
      'Start in plank position',
      'Lower your body until chest nearly touches floor',
      'Push back up to starting position',
      'Keep your core engaged',
    ],
    instructionsKo: [
      '플랭크 자세에서 시작하세요',
      '가슴이 거의 바닥에 닿을 때까지 몸을 낮추세요',
      '시작 자세로 다시 밀어 올리세요',
      '코어에 힘을 유지하세요',
    ],
    checkpoints: [
      {
        name: 'Elbow angle',
        nameKo: '팔꿈치 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['shoulder', 'elbow', 'wrist'],
      },
    ],
    caloriesPerRep: 0.4,
  },
  {
    id: 'plank',
    name: 'Plank',
    nameKo: '플랭크',
    description: 'Core stabilization exercise',
    descriptionKo: '코어 안정화 운동입니다',
    category: 'core',
    difficulty: 'beginner',
    duration: 30,
    defaultReps: 1,
    defaultSets: 3,
    targetMuscles: ['core', 'shoulders', 'glutes'],
    instructions: [
      'Start in forearm plank position',
      'Keep your body in a straight line',
      'Engage your core and glutes',
      'Hold the position',
    ],
    instructionsKo: [
      '팔꿈치 플랭크 자세에서 시작하세요',
      '몸을 일직선으로 유지하세요',
      '코어와 둔근에 힘을 주세요',
      '자세를 유지하세요',
    ],
    checkpoints: [
      {
        name: 'Body alignment',
        nameKo: '몸 정렬',
        startAngle: 180,
        targetAngle: 180,
        completionThreshold: 170,
        joints: ['shoulder', 'hip', 'ankle'],
      },
    ],
    caloriesPerRep: 3,
  },
  {
    id: 'bridge',
    name: 'Bridge',
    nameKo: '브릿지',
    description: 'Glute and core strengthening',
    descriptionKo: '둔근과 코어 강화 운동입니다',
    category: 'core',
    difficulty: 'beginner',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    targetMuscles: ['glutes', 'hamstrings', 'core'],
    instructions: [
      'Lie on your back with knees bent',
      'Lift your hips toward the ceiling',
      'Squeeze your glutes at the top',
      'Lower back down slowly',
    ],
    instructionsKo: [
      '무릎을 구부리고 등을 대고 누우세요',
      '엉덩이를 천장 방향으로 들어올리세요',
      '정점에서 둔근을 조이세요',
      '천천히 내려오세요',
    ],
    checkpoints: [
      {
        name: 'Hip elevation',
        nameKo: '엉덩이 높이',
        startAngle: 90,
        targetAngle: 170,
        completionThreshold: 100,
        joints: ['shoulder', 'hip', 'knee'],
      },
    ],
    caloriesPerRep: 0.3,
  },
]

export const CAPTURE_GUIDES: CaptureGuide[] = [
  {
    direction: 'front',
    instructions: [
      'Stand facing the camera',
      'Keep your arms at your sides',
      'Look straight ahead',
    ],
    instructionsKo: [
      '카메라를 정면으로 바라보고 서세요',
      '팔을 옆에 자연스럽게 내려놓으세요',
      '정면을 바라보세요',
    ],
    checkpoints: ['Full body visible', 'Standing straight', 'Arms visible'],
    checkpointsKo: ['전신이 보임', '똑바로 서 있음', '팔이 보임'],
  },
  {
    direction: 'side',
    instructions: [
      'Stand sideways to the camera',
      'Keep your arms at your sides',
      'Look straight ahead',
    ],
    instructionsKo: [
      '카메라를 향해 옆으로 서세요',
      '팔을 옆에 자연스럽게 내려놓으세요',
      '정면을 바라보세요',
    ],
    checkpoints: ['Full body visible', 'Profile view clear', 'Standing naturally'],
    checkpointsKo: ['전신이 보임', '측면 모습이 선명함', '자연스럽게 서 있음'],
  },
  {
    direction: 'back',
    instructions: [
      'Stand with your back to the camera',
      'Keep your arms at your sides',
      'Look straight ahead',
    ],
    instructionsKo: [
      '카메라에 등을 돌리고 서세요',
      '팔을 옆에 자연스럽게 내려놓으세요',
      '정면을 바라보세요',
    ],
    checkpoints: ['Full body visible', 'Back clearly visible', 'Standing straight'],
    checkpointsKo: ['전신이 보임', '등이 선명하게 보임', '똑바로 서 있음'],
  },
]

export const HAND_EXERCISES = [
  {
    id: 'finger_flexion',
    name: 'Finger Flexion/Extension',
    nameKo: '손가락 굴곡/신전',
    description: 'Open and close your hand completely',
    descriptionKo: '손을 완전히 펴고 주먹을 쥐는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Extend your fingers fully',
      'Slowly make a fist',
      'Hold for 5 seconds then release',
    ],
    guideKo: [
      '손가락을 완전히 펴세요',
      '천천히 주먹을 쥐세요',
      '5초간 유지 후 다시 펴세요',
    ],
  },
  {
    id: 'tendon_glide',
    name: 'Tendon Gliding',
    nameKo: '힘줄 미끄럼 운동',
    description: 'Move through different hand positions',
    descriptionKo: '다양한 손 자세로 이동하는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Start with fingers extended',
      'Curl fingertips toward palm (hook shape)',
      'Extend again then make a fist',
    ],
    guideKo: [
      '손가락을 펴고 시작하세요',
      '손가락 끝을 손바닥 쪽으로 구부리세요 (갈고리 모양)',
      '다시 펴고 주먹을 쥐세요',
    ],
  },
  {
    id: 'thumb_touch',
    name: 'Thumb-to-Finger Touch',
    nameKo: '엄지-손가락 터치',
    description: 'Touch each fingertip with your thumb',
    descriptionKo: '엄지로 각 손가락 끝을 터치하는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Touch thumb tip to index fingertip',
      'Touch thumb tip to middle fingertip',
      'Continue to ring and pinky fingers',
    ],
    guideKo: [
      '엄지와 검지 끝을 터치하세요',
      '엄지와 중지 끝을 터치하세요',
      '엄지와 약지, 소지 순서로 터치하세요',
    ],
  },
  {
    id: 'finger_spread',
    name: 'Finger Spread',
    nameKo: '손가락 벌리기',
    description: 'Spread your fingers apart',
    descriptionKo: '손가락을 최대한 벌리는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Keep all fingers together',
      'Spread fingers as wide as possible',
      'Hold for 5 seconds then bring together',
    ],
    guideKo: [
      '손가락을 모두 붙이세요',
      '손가락을 최대한 벌리세요',
      '5초간 유지 후 다시 모으세요',
    ],
  },
  {
    id: 'grip_squeeze',
    name: 'Grip Squeeze',
    nameKo: '그립 쥐기',
    description: 'Squeeze and hold a fist',
    descriptionKo: '주먹을 쥐고 유지하는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Start with hand open',
      'Squeeze into a tight fist',
      'Hold for 5 seconds then slowly release',
    ],
    guideKo: [
      '손을 편 상태로 시작하세요',
      '주먹을 꽉 쥐세요',
      '5초간 유지 후 천천히 펴세요',
    ],
  },
  {
    id: 'wrist_rotation',
    name: 'Wrist Rotation',
    nameKo: '손목 회전',
    description: 'Rotate your wrist in circles',
    descriptionKo: '손목을 원을 그리며 돌리는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Make a loose fist',
      'Slowly rotate wrist clockwise',
      'Then rotate counter-clockwise',
    ],
    guideKo: [
      '주먹을 가볍게 쥐세요',
      '손목을 시계 방향으로 천천히 돌리세요',
      '반시계 방향으로도 돌리세요',
    ],
  },
]

export const MEDIAPIPE_CONFIG = {
  pose: {
    modelComplexity: 1,
    smoothLandmarks: true,
    enableSegmentation: false,
    smoothSegmentation: false,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5,
  },
  hands: {
    maxNumHands: 2,
    modelComplexity: 1,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5,
  },
}
